spring.application.name=Mi Agenda
spring.datasource.url=${DATABASE_URL:jdbc:sqlite:./agenda.db}
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.datasource.hikari.maximum-pool-size=1

app.secret-key=${SECRET_KEY:cambia-esta-llave-secreta-en-produccion-123456}
app.access-token-expire-minutes=${ACCESS_TOKEN_EXPIRE_MINUTES:60}
